- id: '1590252372642'
  alias: weather_report
  description: ''
  trigger:
  - hours: '0'
    minutes: '26'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度，{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}
    service: tts.baidu_say
  initial_state: true
